
export const listOpcionais =  [
    'Airbag',
    'Alarme',
    'Ar condicionado',
    'Ar quente',
    'Banco com regulagem de altura',
    'Bancos dianteiros com aquecimento',
    'Computador de bordo',
    'Capota marítima',
    'CD e mp3 player',
    'CD player',
    'Computador de bordo',
    'Controle automático de velocidade',
    'Controle de tração',
    'Desembaçador traseiro',
    'Direção hidráulica',
    'Disqueteira',
    'DVD player',
    'Encosto de cabeça traseiro',
    'Farol de xenônio',
    'Freio abs',
    'GPS',
    'Limpador traseiro',
    'Protetor de caçamba',
    'Rádio',
    'Rádio e toca fitas',
    'Retrovisor fotocrômico',
    'Retrovisores elétricos',
    'Rodas de liga leve',
    'Sensor de chuva',
    'Sensor de estacionamento',
    'Teto solar',
    'Tração 4x4',
    'Travas elétricas',
    'Vidros elétricos',
    'Volante com regulagem de altura'
];
